### ISSUE TITLE
Prometheus scraping too much

### ISSUE THREAD

**Issue by ryw** [astronomerio/astronomer-ee#108]
Prometheus should only scrape Kube namespace that Astronomer is installed into.

Steps to reproduce:

Install Astronomer in a k8s cluster that already has an Astronomer running, open up Grafana dashboard, you'll see metrics for activity outside of your Astronomer installation.

**Comment by schnie** [comment]
Lets get this done Monday.

**Comment by schnie** [comment]
I have a fix for this too.

**Comment by schnie** [comment]
This is done. Thought we closed it a while back.
