### ISSUE TITLE
Customer seeing unstable webserver performance

### ISSUE THREAD

**Issue by vparekh94** [astronomerio/astronomer-ee#110]
Customer is experiencing unstable performance with their EE-airflow. @andscoop and I have been looking into it.

What we've tried so far:
- Restarting pods
- Reading through their code.

Problems:
- One of the worker nodes is stuck in a spin crash
- Unstable behavior with the webserver

**Comment by andscoop** [comment]
We resolved the worker issue by first removing the worker volume __from the cloud console__ and then deleting the pod and letting it restore itself.

The webserver is still slow, but it is stable. After reviewing their DAG code it appears that they are making a lot of calls to the postgres database in the top level of the DAGs. This is likely partly responsible for webserver instability.

**Comment by schnie** [comment]
@andscoop did we do anything for the webserver yet? Does it work with our default settings?

Side note - we may have been able to achieve this with `kubectl`, but I've just had a lot more luck blasting things away from from the GKE dashboard when things get stuck, even though it makes no sense. If it happens again we should try again with `kubectl` first, just to see. The issue I've been messing with lately is a little different, so this could be a different type of "stuck".

**Comment by andscoop** [comment]
Not yet, I think removing some top level DAG code that makes calls back to
the postgres database for nearly every DAG, has the potential to speed up
webserver load times.

**Comment by ryw** [comment]
@schnie can we monitor database calls in some way? I know we're considering the database outside of Astronomer, but we should at least write a guide about how to manually monitor Airflow's interaction with your database, and troubleshooting that. this could be core airflow documentation vs. something specific to Astronomer.

**Comment by schnie** [comment]
@ryw I'm guessing this was related to the `/admin/` healthcheck which now pings an actual health url, rather than load all the DAGs. @andscoop @vparekh94 can we close this?

**Comment by ryw** [comment]
possible dupe w/ #111, closing
