### ISSUE TITLE
Logs not making their way into UI

### ISSUE THREAD

**Issue by vparekh94** [astronomerio/astronomer-ee#112]
For both of our customers running EE right now, logs are not making it from the worker to the UI:
```
*** Fetching here: http://positional-planet-8500-worker-1.positional-planet-8500-worker.astronomer.svc.cluster.local:8793/log/srp_scrape_ingestion_20180731/wait_for_raw_srp_scrape_data/2018-08-05T13:00:00/1.log
*** Failed to fetch log file from worker. HTTPConnectionPool(host='positional-planet-8500-worker-1.positional-planet-8500-worker.astronomer.svc.cluster.local', port=8793): Max retries exceeded with url: /log/srp_scrape_ingestion_20180731/wait_for_raw_srp_scrape_data/2018-08-05T13:00:00/1.log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff7a3564f98>: Failed to establish a new connection: [Errno -2] Name does not resolve',))```

Could the webserver be looking in the wrong  place for the logs? I'd consider this bug to be very critical from a customer's perspective.

**Comment by vparekh94** [comment]
Can confirm that these logs are still in the worker pods - can exec in and see them. Could it be something that is bottlenecking the connection between workers and webserver?

**Comment by vparekh94** [comment]
This is not happening  on  my demo instance or on @bonominijl 's cloud instance (only running the test bash dag), so it might have to do with the number of tasks being run.

**Comment by vparekh94** [comment]
Tried this with a new airflow deployment on the cluster and it looks like logs came through there just fine.

@andscoop do you think it could be because of a deleted volume or something else  we got rid of when debugging the instance?

**Comment by schnie** [comment]
@vparekh94 @andscoop if you're looking at task logs that should have been written before deleting a volume, then yes they're def gone. Is this on an instance where we deleting a volume? Looks like it was worker #1.

**Comment by schnie** [comment]
@vparekh94 @andscoop what you guys thinking for this one? Can we close it or are we still seeing ongoing issues?

**Comment by andscoop** [comment]
We should only keep this open if we have evidence that the lost volumes aren't the cause of the missing logs.

**Comment by vparekh94** [comment]
We don't have evidence of that right now, so I agree closing this is the right move for now.
