### ISSUE TITLE
Worker pod stuck in crash loop

### ISSUE THREAD

**Issue by vparekh94** [astronomerio/astronomer-ee#113]
A customer is reporting that a pod is stuck in a crash loop. Getting the logs from kubectl yields:
```
Unable to load the config, contains a configuration error.
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/config.py", line 558, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.6/logging/config.py", line 731, in configure_handler
    result = factory(**kwargs)
  File "/usr/lib/python3.6/site-packages/airflow/utils/log/file_processor_handler.py", line 48, in __init__
    os.makedirs(self._get_log_directory())
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/usr/local/airflow/logs/scheduler'
```
We have fixed this in the past by deleting the workers volume. Is the file system being changed to "read-only" because the volume is out of memory?

**Comment by schnie** [comment]
Is this exactly the same thing we saw last Friday @vparekh94?

**Comment by ryw** [comment]
@vparekh94 can you confirm if this is still broken for customer? is it occurring w/ only one worker? possibly related to full volume or inability to get a volume due to limits?

**Comment by vparekh94** [comment]
It is still broken - I have held off on deleting the volume due to #112 (which is something the customer isn't happy about). Will check and see if they are okay with it.

**Comment by schnie** [comment]
@vparekh94 did you end up deleting the volume and getting it rebooted? We committed a change for the next version that will make the volumes 50Gi instead of 10Gi, but that won't be in until the next version.

**Comment by schnie** [comment]
Aight - well I'll close it for now. Re-open if you come across it again.
