### ISSUE TITLE
Update grafana readiness and liveness endpoint

### ISSUE THREAD

**Issue by bonominijl** [astronomerio/astronomer-ee#115]
The current grafana health checks use `/` for the endpoint, this can cause liveness and readiness checks to fail after enough dashboards are added, >5 as the main page take longer to load. 

Grafana introduced a health endpoint `/api/health` which returns a health payload response:
![screenshot from 2018-08-08 17-07-11](https://user-images.githubusercontent.com/7431155/43864387-898863fa-9b2d-11e8-824d-75024a30527a.png)

**Comment by schnie** [comment]
Fix for this was merged into helm charts, will be included with v0.3.3 release.
