### ISSUE TITLE
Add Ry + Viraj to cloud as sys admin

### ISSUE THREAD

**Issue by bonominijl** [astronomerio/astronomer-ee#118]
```
// List cloud users to retrieve UUID
SELECT * FROM users;`
```
```
// List user groups to retrieve default admin UUID
SELECT * FROM groups WHERE entity_type = 'system';
```
```
// Add user to admin group
INSERT INTO user_group_map (user_uuid, group_uuid) VALUES ('users uuid', 'uuid of admin group');
```

**Comment by schnie** [comment]
Add me too

**Comment by vparekh94** [comment]
Can we add @paolaperaza as well?

**Comment by bonominijl** [comment]
@vparekh94 / @schnie / @ryw / @paolaperaza You've all been added to the `default_admin' group in cloud2 now. This means you should have access to the grafana dashbaord `grafana.astronomer.cloud` and direct access to all airflow deployments, tracked here: https://docs.google.com/spreadsheets/d/1_Scs3ylP0HkVk_J7-Kfg35REuQ0J5fae1eFlFam7CPE/edit#gid=0

You will not have access to the app.astronomer.cloud workspaces, however, unless a user invites you to their workspace.

Remember the words of uncle ben, with great power comes great responsibility. These are production airflow deployments so proceed cautiously.
