### ISSUE TITLE
Control worker count

### ISSUE THREAD

**Issue by schnie** [astronomerio/astronomer-ee#119]
As a deployment.owner I should be able to adjust the amount of celery workers in my deployment.

This should be relatively straightforward. Seems like we need to add a field to the houston requests that gets saved in postgres and gets passed through to helm with the values. Helm charts should already support passing this through. We should put an upper limit on how many someone can provision, maybe like 5 or 10 for now.

- [x] Default to 1 worker, instead of 3
- [x] Add support in Houston/Postgres
- [x] Add slider or similar control to Orbit on deployment creation/edit views
- [ ] Add optional flag to CLI

**Comment by ryw** [comment]
Shipped in 0.7
