### ISSUE TITLE
Control worker size

### ISSUE THREAD

**Issue by schnie** [astronomerio/astronomer-ee#120]
As a deployment.owner I should be able to adjust the worker size between a small, medium or large.

We need to come up with the CPU/MEM requests/limits for the 3 sizes and present this to the user on the deployment creation/edit screen.

- [x] Add support in helm charts for passing in resources requests/limits
- [x] Add support in Houston to pass values during deployment create/edit
- [x] Add support in Orbit views
- [ ] Add support in CLI

**Comment by ryw** [comment]
Shipped in 0.7
