### ISSUE TITLE
Liveness/Readiness probe failing, connection refused

### ISSUE THREAD

**Issue by bonominijl** [astronomerio/astronomer-ee#122]
Seeing an issue similar to #111 the pod is being killed due to failed liveness and readiness checks, however this is due to a connection refused error, rather than a timeout. We're using the `/health` endpoint as with other deployments. I've tried updating back to `/admin/` or `/` with the same error. 

`kubectl describe pod extragalactic-universe-1689-webserver-765c96469f-wzqtq
Name:           extragalactic-universe-1689-webserver-765c96469f-wzqtq
Namespace:      astronomer-cloud
Node:           gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln/10.150.0.7
Start Time:     Tue, 14 Aug 2018 19:29:05 -0400
Labels:         component=webserver
                pod-template-hash=3217520259
                release=extragalactic-universe-1689
                tier=airflow
                workspace=
Annotations:    <none>
Status:         Running
IP:             10.16.5.53
Controlled By:  ReplicaSet/extragalactic-universe-1689-webserver-765c96469f
Containers:
  extragalactic-universe-1689-webserver:
    Container ID:  docker://cdef2566e4680d4bac895ac0e9b3fc0dab6d974030136b648964a8b246be1e23
    Image:         registry.astronomer.cloud/extragalactic-universe-1689/airflow:cli-1
    Image ID:      docker-pullable://registry.astronomer.cloud/extragalactic-universe-1689/airflow@sha256:2cf5f06f6ab15534cf01999904956b9d91c73493e85ad8c6627f7b0078e86c2b
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      airflow
      webserver
    State:          Running
      Started:      Tue, 14 Aug 2018 19:30:47 -0400
    Last State:     Terminated
      Reason:       Error
      Exit Code:    143
      Started:      Tue, 14 Aug 2018 19:30:27 -0400
      Finished:     Tue, 14 Aug 2018 19:30:47 -0400
    Ready:          False
    Restart Count:  4
    Liveness:       http-get http://:8080/ delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:8080/ delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:
      AIRFLOW__CORE__EXECUTOR:                    CeleryExecutor
      AIRFLOW__CELERY__DEFAULT_QUEUE:             celery
      AIRFLOW__SCHEDULER__STATSD_ON:              True
      AIRFLOW__SCHEDULER__STATSD_PORT:            9125
      AIRFLOW__SCHEDULER__STATSD_PREFIX:          airflow
      ASTRONOMER__AIRFLOW__WORKER_LOG_RETENTION:  15
      AIRFLOW__WEBSERVER__BASE_URL:               extragalactic-universe-1689-airflow.astronomer.cloud
      AIRFLOW__SCHEDULER__STATSD_HOST:            extragalactic-universe-1689-statsd
      AIRFLOW__CORE__SQL_ALCHEMY_CONN:            <set to the key 'connection' in secret 'extragalactic-universe-1689-airflow-metadata'>        Optional: false
      AIRFLOW__CELERY__CELERY_RESULT_BACKEND:     <set to the key 'connection' in secret 'extragalactic-universe-1689-airflow-result-backend'>  Optional: false
      AIRFLOW__CELERY__BROKER_URL:                <set to the key 'connection' in secret 'extragalactic-universe-1689-broker-url'>              Optional: false
      AIRFLOW__CORE__FERNET_KEY:                  <set to the key 'fernet-key' in secret 'extragalactic-universe-1689-fernet-key'>              Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-cc6bn (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  default-token-cc6bn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-cc6bn
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age               From                                                          Message
  ----     ------                 ----              ----                                                          -------
  Normal   Scheduled              2m                default-scheduler                                             Successfully assigned extragalactic-universe-1689-webserver-765c96469f-wzqtq to gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln
  Normal   SuccessfulMountVolume  2m                kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln  MountVolume.SetUp succeeded for volume "default-token-cc6bn"
  Normal   Pulled                 1m (x3 over 2m)   kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln  Container image "registry.astronomer.cloud/extragalactic-universe-1689/airflow:cli-1" already present on machine
  Normal   Created                1m (x3 over 1m)   kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln  Created container
  Normal   Started                1m (x3 over 1m)   kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln  Started container
  Warning  Unhealthy              43s (x5 over 1m)  kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln  Readiness probe failed: Get http://10.16.5.53:8080/: dial tcp 10.16.5.53:8080: getsockopt: connection refused
  Warning  Unhealthy              40s (x7 over 1m)  kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln  Liveness probe failed: Get http://10.16.5.53:8080/: dial tcp 10.16.5.53:8080: getsockopt: connection refused
  Normal   Killing                40s (x3 over 1m)  kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln  Killing container with id docker://extragalactic-universe-1689-webserver:Container failed liveness probe.. Container will be killed and recreated.`

**Comment by bonominijl** [comment]
@schnie Seeing this pop up on more airflow deployments. 6 out 0f our 16 airflow deployments in cloud2 are having this issue. Looks like more and more deployments might be breaking the airflow health check.

Airflow deployments experiencing this issue:
`zodiacal-elliptical-5601`
`mathematical-ion-4022`
`frozen-detector-9115`
`extragalactic-universe-1689`
`cislunar-antenna-7244`
`amateur-system-4139`


Pod logs:

`kubectl describe pod zodiacal-elliptical-5601-webserver-87679cddf-pqhrw                                                                                           1 ↵  660  09:56:04
Name:           zodiacal-elliptical-5601-webserver-87679cddf-pqhrw
Namespace:      astronomer-cloud
Node:           gke-astronomer-cloud-astronomer-cloud-d8e891ad-vsv1/10.150.0.7
Start Time:     Thu, 16 Aug 2018 17:46:26 -0400
Labels:         component=webserver
                pod-template-hash=432357889
                release=zodiacal-elliptical-5601
                tier=airflow
                workspace=
Annotations:    <none>
Status:         Running
IP:             10.16.7.17
Controlled By:  ReplicaSet/zodiacal-elliptical-5601-webserver-87679cddf
Containers:
  zodiacal-elliptical-5601-webserver:
    Container ID:  docker://e942bdcb342cd671eafb3aa2d23b7b700b6eb92111229121d9cd643392e20b69
    Image:         registry.astronomer.cloud/zodiacal-elliptical-5601/airflow:cli-4
    Image ID:      docker-pullable://registry.astronomer.cloud/zodiacal-elliptical-5601/airflow@sha256:1edae82b7f57fb308f5fd7d19e087fac6c18e7361d7b310319f8469c34d7cafb
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      airflow
      webserver
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 20 Aug 2018 09:52:53 -0400
      Finished:     Mon, 20 Aug 2018 09:53:23 -0400
    Ready:          False
    Restart Count:  342
    Liveness:       http-get http://:8080/health delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:8080/health delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:
      AIRFLOW__CORE__EXECUTOR:                    CeleryExecutor
      AIRFLOW__CELERY__DEFAULT_QUEUE:             celery
      AIRFLOW__SCHEDULER__STATSD_ON:              True
      AIRFLOW__SCHEDULER__STATSD_PORT:            9125
      AIRFLOW__SCHEDULER__STATSD_PREFIX:          airflow
      ASTRONOMER__AIRFLOW__WORKER_LOG_RETENTION:  15
      AIRFLOW__WEBSERVER__BASE_URL:               zodiacal-elliptical-5601-airflow.astronomer.cloud
      AIRFLOW__SCHEDULER__STATSD_HOST:            zodiacal-elliptical-5601-statsd
      AIRFLOW__CORE__SQL_ALCHEMY_CONN:            <set to the key 'connection' in secret 'zodiacal-elliptical-5601-airflow-metadata'>        Optional: false
      AIRFLOW__CELERY__CELERY_RESULT_BACKEND:     <set to the key 'connection' in secret 'zodiacal-elliptical-5601-airflow-result-backend'>  Optional: false
      AIRFLOW__CELERY__BROKER_URL:                <set to the key 'connection' in secret 'zodiacal-elliptical-5601-broker-url'>              Optional: false
      AIRFLOW__CORE__FERNET_KEY:                  <set to the key 'fernet-key' in secret 'zodiacal-elliptical-5601-fernet-key'>              Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-cc6bn (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  default-token-cc6bn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-cc6bn
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                 From                                                          Message
  ----     ------     ----                ----                                                          -------
  Warning  Unhealthy  38m (x939 over 3d)  kubelet, gke-astronomer-cloud-astronomer-cloud-d8e891ad-vsv1  Readiness probe failed: Get http://10.16.7.17:8080/health: dial tcp 10.16.7.17:8080: getsockopt: connection refused
  Warning  BackOff    14m (x546 over 2d)  kubelet, gke-astronomer-cloud-astronomer-cloud-d8e891ad-vsv1  Back-off restarting failed container
  Warning  Unhealthy  9m (x917 over 3d)   kubelet, gke-astronomer-cloud-astronomer-cloud-d8e891ad-vsv1  Liveness probe failed: Get http://10.16.7.17:8080/health: dial tcp 10.16.7.17:8080: getsockopt: connection refused
  Normal   Pulled     4m (x341 over 3d)   kubelet, gke-astronomer-cloud-astronomer-cloud-d8e891ad-vsv1  Container image "registry.astronomer.cloud/zodiacal-elliptical-5601/airflow:cli-4" already present on machine
`

`
 cerebro@cerebral  ~  kubectl describe pod frozen-detector-9115-webserver-5476b8ccc6-xtwmj                                                                                                ✔  661  09:56:10
Name:           frozen-detector-9115-webserver-5476b8ccc6-xtwmj
Namespace:      astronomer-cloud
Node:           gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-1rh6/10.150.0.3
Start Time:     Fri, 10 Aug 2018 18:13:38 -0400
Labels:         component=webserver
                pod-template-hash=1032647772
                release=frozen-detector-9115
                tier=airflow
                workspace=
Annotations:    <none>
Status:         Running
IP:             10.16.0.16
Controlled By:  ReplicaSet/frozen-detector-9115-webserver-5476b8ccc6
Containers:
  frozen-detector-9115-webserver:
    Container ID:  docker://67b3ceba30aaed6ca517a8cdfe952208251e0875f3c2af1a95e15a20e92f1e2f
    Image:         registry.astronomer.cloud/frozen-detector-9115/airflow:cli-1
    Image ID:      docker-pullable://registry.astronomer.cloud/frozen-detector-9115/airflow@sha256:a693b3884f966283ca8021e805d9c28d91e893a514899202e71a027c20f3c82a
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      airflow
      webserver
    State:          Running
      Started:      Mon, 20 Aug 2018 09:34:13 -0400
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 20 Aug 2018 09:26:04 -0400
      Finished:     Mon, 20 Aug 2018 09:34:13 -0400
    Ready:          True
    Restart Count:  344
    Liveness:       http-get http://:8080/health delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:8080/health delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:
      AIRFLOW__CORE__EXECUTOR:                    CeleryExecutor
      AIRFLOW__CELERY__DEFAULT_QUEUE:             celery
      AIRFLOW__SCHEDULER__STATSD_ON:              True
      AIRFLOW__SCHEDULER__STATSD_PORT:            9125
      AIRFLOW__SCHEDULER__STATSD_PREFIX:          airflow
      ASTRONOMER__AIRFLOW__WORKER_LOG_RETENTION:  15
      AIRFLOW__WEBSERVER__BASE_URL:               frozen-detector-9115-airflow.astronomer.cloud
      AIRFLOW__SCHEDULER__STATSD_HOST:            frozen-detector-9115-statsd
      AIRFLOW__CORE__SQL_ALCHEMY_CONN:            <set to the key 'connection' in secret 'frozen-detector-9115-airflow-metadata'>        Optional: false
      AIRFLOW__CELERY__CELERY_RESULT_BACKEND:     <set to the key 'connection' in secret 'frozen-detector-9115-airflow-result-backend'>  Optional: false
      AIRFLOW__CELERY__BROKER_URL:                <set to the key 'connection' in secret 'frozen-detector-9115-broker-url'>              Optional: false
      AIRFLOW__CORE__FERNET_KEY:                  <set to the key 'fernet-key' in secret 'frozen-detector-9115-fernet-key'>              Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-cc6bn (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  default-token-cc6bn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-cc6bn
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                 From                                                          Message
  ----     ------     ----                ----                                                          -------
  Warning  Unhealthy  22m (x821 over 4d)  kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-1rh6  Readiness probe failed: Get http://10.16.0.16:8080/health: dial tcp 10.16.0.16:8080: getsockopt: connection refused
  Warning  Unhealthy  22m (x869 over 4d)  kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-1rh6  Liveness probe failed: Get http://10.16.0.16:8080/health: dial tcp 10.16.0.16:8080: getsockopt: connection refused
`

`
 cerebro@cerebral  ~  kubectl describe pod extragalactic-universe-1689-webserver-55c6d867d7-4xnc5                                                                                         ✔  662  09:56:35
Name:           extragalactic-universe-1689-webserver-55c6d867d7-4xnc5
Namespace:      astronomer-cloud
Node:           gke-astronomer-cloud-astronomer-cloud-d8e891ad-blhd/10.150.0.5
Start Time:     Tue, 14 Aug 2018 20:23:15 -0400
Labels:         component=webserver
                pod-template-hash=1172842383
                release=extragalactic-universe-1689
                tier=airflow
                workspace=
Annotations:    <none>
Status:         Running
IP:             10.16.2.49
Controlled By:  ReplicaSet/extragalactic-universe-1689-webserver-55c6d867d7
Containers:
  extragalactic-universe-1689-webserver:
    Container ID:  docker://ef0de4a7f45ce876f58701c7622fd043bfa4dcbee1c5f41c5bdb6bdf6bdbbd2f
    Image:         astronomerinc/ap-airflow:0.3.2
    Image ID:      docker-pullable://astronomerinc/ap-airflow@sha256:0664d5de75f4095d1c5364c7a27be5e17d200b177066cf7107e77fb97bf302d6
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      airflow
      webserver
    State:          Running
      Started:      Mon, 20 Aug 2018 09:44:23 -0400
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 20 Aug 2018 09:28:33 -0400
      Finished:     Mon, 20 Aug 2018 09:44:22 -0400
    Ready:          True
    Restart Count:  314
    Liveness:       http-get http://:8080/health delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:8080/health delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:
      AIRFLOW__CORE__EXECUTOR:                    CeleryExecutor
      AIRFLOW__CELERY__DEFAULT_QUEUE:             celery
      AIRFLOW__SCHEDULER__STATSD_ON:              True
      AIRFLOW__SCHEDULER__STATSD_PORT:            9125
      AIRFLOW__SCHEDULER__STATSD_PREFIX:          airflow
      ASTRONOMER__AIRFLOW__WORKER_LOG_RETENTION:  14
      AIRFLOW__WEBSERVER__BASE_URL:               extragalactic-universe-1689-airflow.astronomer.cloud
      AIRFLOW__SCHEDULER__STATSD_HOST:            extragalactic-universe-1689-statsd
      AIRFLOW__CORE__SQL_ALCHEMY_CONN:            <set to the key 'connection' in secret 'extragalactic-universe-1689-airflow-metadata'>        Optional: false
      AIRFLOW__CELERY__CELERY_RESULT_BACKEND:     <set to the key 'connection' in secret 'extragalactic-universe-1689-airflow-result-backend'>  Optional: false
      AIRFLOW__CELERY__BROKER_URL:                <set to the key 'connection' in secret 'extragalactic-universe-1689-broker-url'>              Optional: false
      AIRFLOW__CORE__FERNET_KEY:                  <set to the key 'fernet-key' in secret 'extragalactic-universe-1689-fernet-key'>              Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-cc6bn (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  default-token-cc6bn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-cc6bn
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                 From                                                          Message
  ----     ------     ----                ----                                                          -------
  Warning  BackOff    43m (x438 over 4d)  kubelet, gke-astronomer-cloud-astronomer-cloud-d8e891ad-blhd  Back-off restarting failed container
  Warning  Unhealthy  12m (x815 over 4d)  kubelet, gke-astronomer-cloud-astronomer-cloud-d8e891ad-blhd  Liveness probe failed: Get http://10.16.2.49:8080/health: dial tcp 10.16.2.49:8080: getsockopt: connection refused
  Warning  Unhealthy  12m (x736 over 4d)  kubelet, gke-astronomer-cloud-astronomer-cloud-d8e891ad-blhd  Readiness probe failed: Get http://10.16.2.49:8080/health: dial tcp 10.16.2.49:8080: getsockopt: connection refused
`

`
 cerebro@cerebral  ~  kubectl describe pod cislunar-antenna-7244-webserver-746d6fbc78-sqsct                                                                                               ✔  663  09:56:49
Name:           cislunar-antenna-7244-webserver-746d6fbc78-sqsct
Namespace:      astronomer-cloud
Node:           gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-1rh6/10.150.0.3
Start Time:     Fri, 10 Aug 2018 18:13:36 -0400
Labels:         component=webserver
                pod-template-hash=3028296734
                release=cislunar-antenna-7244
                tier=airflow
                workspace=
Annotations:    <none>
Status:         Running
IP:             10.16.0.3
Controlled By:  ReplicaSet/cislunar-antenna-7244-webserver-746d6fbc78
Containers:
  cislunar-antenna-7244-webserver:
    Container ID:  docker://f93acf723ef52d4762af13e2867d4429c515ec34f152050190a0593b97be5126
    Image:         astronomerinc/ap-airflow:0.3.2
    Image ID:      docker-pullable://astronomerinc/ap-airflow@sha256:0664d5de75f4095d1c5364c7a27be5e17d200b177066cf7107e77fb97bf302d6
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      airflow
      webserver
    State:          Running
      Started:      Mon, 20 Aug 2018 09:51:52 -0400
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 20 Aug 2018 09:40:22 -0400
      Finished:     Mon, 20 Aug 2018 09:51:52 -0400
    Ready:          True
    Restart Count:  365
    Liveness:       http-get http://:8080/health delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:8080/health delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:
      AIRFLOW__CORE__EXECUTOR:                    CeleryExecutor
      AIRFLOW__CELERY__DEFAULT_QUEUE:             celery
      AIRFLOW__SCHEDULER__STATSD_ON:              True
      AIRFLOW__SCHEDULER__STATSD_PORT:            9125
      AIRFLOW__SCHEDULER__STATSD_PREFIX:          airflow
      ASTRONOMER__AIRFLOW__WORKER_LOG_RETENTION:  15
      AIRFLOW__WEBSERVER__BASE_URL:               cislunar-antenna-7244-airflow.astronomer.cloud
      AIRFLOW__SCHEDULER__STATSD_HOST:            cislunar-antenna-7244-statsd
      AIRFLOW__CORE__SQL_ALCHEMY_CONN:            <set to the key 'connection' in secret 'cislunar-antenna-7244-airflow-metadata'>        Optional: false
      AIRFLOW__CELERY__CELERY_RESULT_BACKEND:     <set to the key 'connection' in secret 'cislunar-antenna-7244-airflow-result-backend'>  Optional: false
      AIRFLOW__CELERY__BROKER_URL:                <set to the key 'connection' in secret 'cislunar-antenna-7244-broker-url'>              Optional: false
      AIRFLOW__CORE__FERNET_KEY:                  <set to the key 'fernet-key' in secret 'cislunar-antenna-7244-fernet-key'>              Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-cc6bn (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  default-token-cc6bn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-cc6bn
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                 From                                                          Message
  ----     ------     ----                ----                                                          -------
  Warning  Unhealthy  5m (x740 over 9d)   kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-1rh6  Readiness probe failed: Get http://10.16.0.3:8080/health: dial tcp 10.16.0.3:8080: getsockopt: connection refused
  Warning  Unhealthy  5m (x1117 over 9d)  kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-1rh6  Liveness probe failed: Get http://10.16.0.3:8080/health: dial tcp 10.16.0.3:8080: getsockopt: connection refused
`

`
 cerebro@cerebral  ~  kubectl describe pod amateur-system-4139-webserver-5fddf9f487-z26m9                                                                                                 ✔  664  09:57:06
Name:           amateur-system-4139-webserver-5fddf9f487-z26m9
Namespace:      astronomer-cloud
Node:           gke-astronomer-cloud-astronomer-cloud-d8e891ad-vsv1/10.150.0.7
Start Time:     Fri, 17 Aug 2018 11:02:31 -0400
Labels:         component=webserver
                pod-template-hash=1988959043
                release=amateur-system-4139
                tier=airflow
                workspace=
Annotations:    <none>
Status:         Running
IP:             10.16.7.20
Controlled By:  ReplicaSet/amateur-system-4139-webserver-5fddf9f487
Containers:
  amateur-system-4139-webserver:
    Container ID:  docker://b994e32df19a525094a7f16d66d0762cda2b33696067dc61445ad1d9db3b622d
    Image:         registry.astronomer.cloud/amateur-system-4139/airflow:cli-10
    Image ID:      docker-pullable://registry.astronomer.cloud/amateur-system-4139/airflow@sha256:185616f7016366556e03f8b7d20daa3d3cc6675da5a550c0b607df8b6e92a2c2
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      airflow
      webserver
    State:          Running
      Started:      Mon, 20 Aug 2018 09:48:02 -0400
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 20 Aug 2018 09:47:32 -0400
      Finished:     Mon, 20 Aug 2018 09:48:01 -0400
    Ready:          True
    Restart Count:  384
    Liveness:       http-get http://:8080/health delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:8080/health delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:
      AIRFLOW__CORE__EXECUTOR:                    CeleryExecutor
      AIRFLOW__CELERY__DEFAULT_QUEUE:             celery
      AIRFLOW__SCHEDULER__STATSD_ON:              True
      AIRFLOW__SCHEDULER__STATSD_PORT:            9125
      AIRFLOW__SCHEDULER__STATSD_PREFIX:          airflow
      ASTRONOMER__AIRFLOW__WORKER_LOG_RETENTION:  15
      AIRFLOW__WEBSERVER__BASE_URL:               amateur-system-4139-airflow.astronomer.cloud
      AIRFLOW__SCHEDULER__STATSD_HOST:            amateur-system-4139-statsd
      AIRFLOW__CORE__SQL_ALCHEMY_CONN:            <set to the key 'connection' in secret 'amateur-system-4139-airflow-metadata'>        Optional: false
      AIRFLOW__CELERY__CELERY_RESULT_BACKEND:     <set to the key 'connection' in secret 'amateur-system-4139-airflow-result-backend'>  Optional: false
      AIRFLOW__CELERY__BROKER_URL:                <set to the key 'connection' in secret 'amateur-system-4139-broker-url'>              Optional: false
      AIRFLOW__CORE__FERNET_KEY:                  <set to the key 'fernet-key' in secret 'amateur-system-4139-fernet-key'>              Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-cc6bn (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  default-token-cc6bn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-cc6bn
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                  From                                                          Message
  ----     ------     ----                 ----                                                          -------
  Warning  Unhealthy  24m (x743 over 2d)   kubelet, gke-astronomer-cloud-astronomer-cloud-d8e891ad-vsv1  Readiness probe failed: Get http://10.16.7.20:8080/health: dial tcp 10.16.7.20:8080: getsockopt: connection refused
  Warning  Unhealthy  10m                  kubelet, gke-astronomer-cloud-astronomer-cloud-d8e891ad-vsv1  Readiness probe failed: Get http://10.16.7.20:8080/health: read tcp 10.150.0.7:58468->10.16.7.20:8080: read: connection reset by peer
  Warning  Unhealthy  10m (x1163 over 2d)  kubelet, gke-astronomer-cloud-astronomer-cloud-d8e891ad-vsv1  Liveness probe failed: Get http://10.16.7.20:8080/health: dial tcp 10.16.7.20:8080: getsockopt: connection refused
  Normal   Killing    9m (x358 over 2d)    kubelet, gke-astronomer-cloud-astronomer-cloud-d8e891ad-vsv1  Killing container with id docker://amateur-system-4139-webserver:Container failed liveness probe.. Container will be killed and recreated.`

**Comment by schnie** [comment]
@bonominijl are you still seeing this after the db upgrade today?

**Comment by bonominijl** [comment]
@schnie Hard to say. I didn't take an exact restart count of each to compare to today. I just deleted the webserver pods to reset their restart count and I'll monitor today. I've we're still seeing the same number of restarts it should be obvious in a few hours.
