### ISSUE TITLE
Control worker termination grace period

### ISSUE THREAD

**Issue by schnie** [astronomerio/astronomer-ee#123]
As a deployment.owner I should be able to set the grace period for my workers to restart during a code push.

Default now is 10 minutes, maybe we should offer another slider up to a certain max. Maybe an hour for now, maybe longer depending on current customer needs.

**Comment by cwurtz** [comment]
Support for this has been added to houston.  Since there are no UI/CLI parts to this issue, I am closing it.

**Comment by cwurtz** [comment]
Just didn't know if it was this issue or another

**Comment by pcmaffey** [comment]
Done in UI as well. Can close when tested.

**Comment by ryw** [comment]
Shipped in 0.7
