### ISSUE TITLE
Silent failures in New Cloud

### ISSUE THREAD

**Issue by vparekh94** [astronomerio/astronomer-ee#125]
Tasks are silently failing on Cloud 2.0, my gut says it is due to database connection issues:

Errors like these are making it into the UI:
```Broken DAG: [/usr/local/airflow/dags/s3_loader_delivery_settings/product_delivery_settings.py] (psycopg2.OperationalError) FATAL: remaining connection slots are reserved for non-replication superuser connections (Background on this error at: http://sqlalche.me/e/e3q8)```

Task logs for a failed task are also blank:

![image](https://user-images.githubusercontent.com/19679395/44345027-1a4efd00-a460-11e8-93bd-ee23775268e4.png)

**Comment by bonominijl** [comment]
@vparekh94 / @schnie  I had an example dag running in one of my test instances and it looks like it was using 60 active connections to run that DAG. We should rework our example DAG to use fewer active connections and encourage any customer still running the example to turn it off. 

I deleted that and another deployment I had, we're now using ~220 of our 300 max connections to the Cloud SQL postgres

**Comment by vparekh94** [comment]
From a customer:
```
a pattern that we found works that could work for you is:

Container Application -> PgBouncer -> Postgres
Container Application -> Seperate PgBouncer -> Postgres
you could sidecar pgbouncer?
```

The issue we are facing looks similar to:
https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/88

it looks like pgbouncer handles the connection pooling - could be worth giving that shot

**Comment by schnie** [comment]
Nice, looking into pgbouncer and other options today

**Comment by ryw** [comment]
@schnie has pgbouncer solution ready to go out with next release

**Comment by paolaperaza** [comment]
@schnie sounds like we can close this, given the 0.5.1 release?

**Comment by schnie** [comment]
Yep!
