### ISSUE TITLE
Log URLs in Astronomer Cloud 404

### ISSUE THREAD

**Issue by KevinGreene** [astronomerio/astronomer-ee#130]
Using the new Astronomer Cloud, all log URLs accessible from admin/taskinstance appear to 404.

The href element in question is:

```
<a href="instance-1234-airflow.astronomer.cloud/admin/airflow/log?dag_id=airflow_info&amp;task_id=disk_space&amp;execution_date=2018-09-07T14:46:02.511905">    <span class="glyphicon glyphicon-book" aria-hidden="true" data-original-title="" title=""></span></a>
```

As a result, when I click the link it directs me to:

```
https://instance-1234-airflow.astronomer.cloud/admin/taskinstance/instance-1234-airflow.astronomer.cloud/admin/airflow/log?dag_id=airflow_info&task_id=disk_space&execution_date=2018-09-07T14:46:02.511905
```

I think this can be fixed by updating wherever it pulls the href from to include `https://` or even just `//`.

**Comment by schnie** [comment]
@bonominijl are you seeing this in all instances?

**Comment by paolaperaza** [comment]
Thanks @JohnLemberger and @KevinGreene for getting this in writing. 

@schnie - any idea what our path forward is for this one, from our end?

**Comment by paolaperaza** [comment]
@schnie Just tested this on a few, and I'm seeing it for all the cloud 2 instances I've jumped into thus far. 

If you go into task instances > logs on the right per the screenshot above, the URL looks doubled.

If I remove the first part of it (e.g. `old-rocket-1234-airflow.astronomer.cloud`) and leave the rest (which will begin with the same thing, but end with `/admin/airflow/log?/dag_id=doc_com_transfer&task_id=`....), it'll load successfully. 

Think someone can tackle this?

**Comment by schnie** [comment]
@paolaperaza ah thanks for digging into it, I was able to recreate as well. We'll look into it and report back soon. Should have something figured out soon.

**Comment by schnie** [comment]
Ok, tracked this down. Will have a fix out for v0.5.1 in the next day or so.

**Comment by paolaperaza** [comment]
Thanks so much for looking into this offline, @schnie ! That's great to hear. I'll keep an eye out for that fix and alert customers/close this issue accordingly.

**Comment by schnie** [comment]
Fixed with https://github.com/astronomerio/helm.astronomer.io/pull/91
