### ISSUE TITLE
Enterprise Airflow on AWS

### ISSUE THREAD

**Issue by ryw** [astronomerio/astronomer-ee#17]
* We'll probably need to run our own Kubernetes for this, for now.

**Comment by ryw** [comment]
@schnie we're going to probably need to help these early customers get Kubernetes running on AWS perhaps via Typhoon (which includes Terraform scripts) - do you want to do first exploration of the idea, or we can assign to a dev.

Empty page for guide created here: http://enterprise.astronomer.io/guides/aws/

**Comment by tedmiston** [comment]
@schnie @ryw Thoughts on punting this from this sprint?

I read through the typhoon docs and discussed with Greg yesterday.  While it looks cool, it's a small/early project (11 contributors, almost all 1 guy) but more importantly the day 2 ops are more work to maintain than using managed Kubernetes on GCP.

Is it realistic to push people towards that path until AWS has EKS/Fargate in GA?

**Comment by schnie** [comment]
I think pushing it makes sense. Feel like we have higher priorities and really don't want to support non-managed kubernetes workloads.

**Comment by ryw** [comment]
moved out of milestone
