### ISSUE TITLE
Add ability to duplicate pools, variables and connections between two Airflow instances

### ISSUE THREAD

**Issue by andscoop** [astronomerio/astronomer-ee#18]
As a user of the Astronomer Enterprise, I would like to be able to migrate pools, connection information and Airflow Variables between various Airflow instances, in order to save significant amounts of time when deploying airflow instances for many teams or users in a single organization or team.

possible cli cmd
`astro airflow copy [src-instance-release-name] [dst-instance-release-name] [args]`

possible arguments

-a | copy all possibilities between instances
-v | copy airflow variables between instances
-c | copy airflow connections between instances
-p | copy airflow pools between instances

Each argument could also take an optional fp to point to a json file whitelisting all pools, connections and variables by key that need to be copied. This would prevent sensitive connections on one instance from being copied while allowing user to copy everything else.

**Comment by benjamingregory** [comment]
Copying connection info would be 💯

**Comment by ryw** [comment]
Issue moved to [astronomerio/astro-cli #91](https://github.com/astronomerio/astro-cli/issues/91) via [**ZenHub**](https://www.zenhub.com/)
