### ISSUE TITLE
Beef up homepage for enterprise.astronomer.io

### ISSUE THREAD

**Issue by ryw** [astronomerio/astronomer-ee#21]
good models:
* https://enterprise.github.com
* https://www.confluent.io/product/confluent-enterprise/
* https://about.gitlab.com/gitlab-ee/

**Comment by gregbrunk** [comment]
Issue moved to [astronomerio/website #282](https://github.com/astronomerio/website/issues/282) via [**ZenHub**](https://www.zenhub.com/)
