### ISSUE TITLE
Automate publishing docs via CircleCI

### ISSUE THREAD

**Issue by schnie** [astronomerio/astronomer-ee#30]
Set up circle to build and push docs.

**Comment by schnie** [comment]
I was thinking we could create a GCP service account. If you're able to work on this, I can get one created that can push to those buckets.

**Comment by tedmiston** [comment]
Yeah, I can do it but probably in the next sprint if that works.

I wrote a doc on Friday that adds the manual build instructions I'll push up in the mean time.
