### ISSUE TITLE
Update NGINX ingress to pass auth headers

### ISSUE THREAD

**Issue by cwurtz** [astronomerio/astronomer-ee#31]
For components like Airflow and Grafana, we'll need to pass a header containing the authenticated user's username and email.

It should add the headers `X-PROXY-AUTH-USER`and `X-PROXY-AUTH-EMAIL`, where the former is the username, and the later is the email

NGINX will also need to scrub these headers from incoming requests to ensure that it is the only way for ingress requests to have this header set.

**Comment by ryw** [comment]
this is done, right @cwurtz?

**Comment by cwurtz** [comment]
It's not, but in the current setup it isn't necessary, at least not in the same context the issue was created for.  Closing it is fine
