### ISSUE TITLE
Pushing your first DAG/ Getting Started Doc

### ISSUE THREAD

**Issue by andscoop** [astronomerio/astronomer-ee#41]
Doc will include

- Initiating your first project
  - pointing your project to the appropriate registry (will be temporary until more features added to cli)
- What's in your project directory after `astro airflow init`
- Pushing your first DAG

Other Task Involved
- Review how Doc fits in with Migrating DAGs doc

**Comment by benjamingregory** [comment]
Happy to help with example dags, etc. if you need assistance. 

Could be a different issue though.

**Comment by andscoop** [comment]
@vparekh94 Would you be able to review this doc for content. I have changed the scope of this particular doc to only include project initialization and running it locally. I think deployment to a cluster should be it's own doc.

https://github.com/astronomerio/astronomer-ee/blob/feature/41-pushing-your-first-dag-guide/docs/pages/guides/creating-an-ee-project.md

**Comment by vparekh94** [comment]
@andscoop I like separating initializing from deploying - it definitely makes things a little clear. Only questions are:

1) Do you think that `packages.txt` should get a little blurb too?
2) Anything I can do to help with the Deploying doc?

**Comment by andscoop** [comment]
@vparekh94 It probably should - I can finish that this week.

I do think that `packages.txt` should get a blurb. Would you be interested in doing that one since I haven't had any direct experience with it?
