### ISSUE TITLE
Hookup EE Docs to Circle CI

### ISSUE THREAD

**Issue by andscoop** [astronomerio/astronomer-ee#46]
We will want to configure EE for circle-ci so that we can do automated builds and pushes to our GCP bucket.

**Comment by tedmiston** [comment]
@andscoop I have time carved out to do this next week for EE & Open - https://github.com/astronomerio/astronomer-ee/issues/30 https://github.com/astronomerio/astronomer/issues/31.

**Comment by tedmiston** [comment]
Closing as dupe
