### ISSUE TITLE
Create CI/CD Documentation

### ISSUE THREAD

**Issue by andscoop** [astronomerio/astronomer-ee#58]
We need a guide detailing how to deploy to Astronomer EE using CI/CD.

Will this doc replicate what astro-cli does under the hood? Or will it alternatively leverage astro-cli as an interface to accomplish all of this? If going route 2 - create appropriate issues in astro-cli to allow the CLI to accomplish this

**Comment by tedmiston** [comment]
done https://github.com/astronomerio/astronomer-ee/blob/6aea7c3c878cea529dc89e7917e4c3587310aeda/docs/pages/guides/deploying-dags-with-cicd.md
