### ISSUE TITLE
Specify install location

### ISSUE THREAD

**Issue by vparekh94** [astronomerio/astronomer-ee#60]
We've had a few customers attempt to deploy the CLI on remote boxes (cloud compute boxes, EC2s, etc.)

There's something in the install that breaks these. 

We should make it clear that the CLI is meant for a local machine.

**Comment by vparekh94** [comment]
Update - they were able to install it using the go binary instead of the curl command - no idea why. Not assigning to anyone because it doesn't seem urgent, but eventually we should look into this.

**Comment by ryw** [comment]
Issue moved to [astronomerio/astro-cli #93](https://github.com/astronomerio/astro-cli/issues/93) via [**ZenHub**](https://www.zenhub.com/)
