### ISSUE TITLE
Trouble with google-cloud-data-flow

### ISSUE THREAD

**Issue by vparekh94** [astronomerio/astronomer-ee#62]
google-cloud data-flow causes issues when deploying. Error message:

```
 Could not find a version that satisfies the requirement apache-beam[gcp]==2.4.0 (from google-cloud-dataflow>=2.2.0->-r requirements.txt (line 7)) (from versions: 0.6.0, 2.0.0, 2.1.0, 2.1.1, 2.2.0)
No matching distribution found for apache-beam[gcp]==2.4.0 (from google-cloud-dataflow>=2.2.0->-r requirements.txt (line 7))
The command '/bin/sh -c pip install --no-cache-dir -q -r requirements.txt' returned a non-zero code: 1
panic: exit status 1
```

**Comment by schnie** [comment]
@andscoop @tedmiston you guy know if this is related to https://github.com/astronomerio/astronomer/pull/46?

**Comment by vparekh94** [comment]
@schnie I'm pretty sure it is.  Andy mentioned to them in an email we're waiting to pull in the fix - I'm just trying to do a better job of documenting all issues/concerns that have come up in installs on GH.

**Comment by andscoop** [comment]
Slightly, it is the same customer. The fix for #46 allowed the customer to move forward when he omitted dataflow from his `requirements.txt` (listed below). This issue is for the error that happens when leaving dataflow in the `requirements.txt`

**Customer Log Dump**
```
 ---> Running in 4bf930c2f20e
  Could not find a version that satisfies the requirement apache-beam[gcp]==2.4.0 (from google-cloud-dataflow>=2.2.0->-r requirements.txt (line 7)) (from versions: 0.6.0, 2.0.0, 2.1.0, 2.1.1, 2.2.0)
No matching distribution found for apache-beam[gcp]==2.4.0 (from google-cloud-dataflow>=2.2.0->-r requirements.txt (line 7))
The command '/bin/sh -c pip install --no-cache-dir -q -r requirements.txt' returned a non-zero code: 1
panic: exit status 1

So from this it seems there's a bad dataflow import and I see come stuff in the changelog about that, luckily we're not using that so I can remove that requirement. Which leads to this cryptic message:

Removing intermediate container 047908f438a4
 ---> Running in a33a309f5e7c
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-bcd7nyyg/googleapis-common-protos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-h03qokqz-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-bcd7nyyg/googleapis-common-protos/
The command '/bin/sh -c pip install --no-cache-dir -q -r requirements.txt' returned a non-zero code: 1
panic: exit status 1
```

**Customer requirements.txt**
```
httplib2
google-api-python-client>=1.5.0, <1.6.0
oauth2client>=2.0.2, <2.1.0
PyOpenSSL
google-cloud-dataflow>=2.2.0
pandas-gbq
```

**Comment by tedmiston** [comment]
I think this is unrelated to setuptools.

His first command says he's trying to install `apache-beam[gcp]==2.4.0`.  When I run a pip install on that package, the latest version that exists is 2.2.0.

```
$ pip install apache-beam==99999 --no-cache-dir
Collecting apache-beam==99999
  Could not find a version that satisfies the requirement apache-beam==99999 (from versions: 0.6.0, 2.0.0, 2.1.0, 2.1.1, 2.2.0)
No matching distribution found for apache-beam==99999
$ pip --version
pip 9.0.3 from /Users/taylor/.local/share/virtualenvs/tmp-ca583f74fdce3a8/lib/python3.6/site-packages (python 3.6)
```

(The 99999 is a hack to get it to show all versions.)

Even trying to install pre-release versions, I'm not getting one newer than 2.2.0.

```
$ pip install apache-beam --pre
```

However, I can see the [2.4.0 release](https://pypi.python.org/pypi/apache-beam) on PyPI.  It could be something is wrong with that release.  If so we could switch our install to pull from GitHub @ https://github.com/apache/beam/tree/v2.4.0/sdks/python.

This could be a quirk of the enterprise network over here.

Can someone else confirm that they get the same output running this command on their machine?

Assuming this is a fluke and the PyPI version does exist, this could be an incompatible dependency we have installed underneath, something gcp related probably.

**Comment by tedmiston** [comment]
The second message in the customer's log is the `googleapis-common-protos` package failing to build because one of its dependencies failed to be met, presumably related to `apache-beam` or something it would have installed had it succeeded.

**Comment by vparekh94** [comment]
@tedmiston just ran:
`pip install apache-beam`

It tried to download 2.2.0, but failed due to some Cython issue.

2.4.0 is what the googleapis tries to pull

**Comment by tedmiston** [comment]
Cython issue probably some dependency failed to build.  Can you paste your error logs?

**Comment by vparekh94** [comment]
```
Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        For performance reasons, doesn't actually impose an ordering
        on unequal values (always returning 1).
        """
        if type(left) is not type(right):
          return cmp(type(left), type(right))
                   ^
    ------------------------------------------------------------
    
    apache_beam/utils/windowed_value.py:83:16: undeclared name not builtin: cmp
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9m09xu0m/apache-beam/setup.py", line 173, in <module>
        'apache_beam/utils/windowed_value.py',
      File "/home/virajparekh/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1027, in cythonize
        cythonize_one(*args)
      File "/home/virajparekh/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1149, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: apache_beam/utils/windowed_value.py
    Compiling apache_beam/coders/stream.pyx because it changed.
    Compiling apache_beam/runners/worker/statesampler.pyx because it changed.
    Compiling apache_beam/coders/coder_impl.py because it changed.
    Compiling apache_beam/metrics/execution.py because it changed.
    Compiling apache_beam/runners/common.py because it changed.
    Compiling apache_beam/runners/worker/logger.py because it changed.
    Compiling apache_beam/runners/worker/opcounters.py because it changed.
    Compiling apache_beam/runners/worker/operations.py because it changed.
    Compiling apache_beam/transforms/cy_combiners.py because it changed.
    Compiling apache_beam/utils/counters.py because it changed.
    Compiling apache_beam/utils/windowed_value.py because it changed.
    [ 1/11] Cythonizing apache_beam/coders/coder_impl.py
    [ 2/11] Cythonizing apache_beam/coders/stream.pyx
    [ 3/11] Cythonizing apache_beam/metrics/execution.py
    [ 4/11] Cythonizing apache_beam/runners/common.py
    [ 5/11] Cythonizing apache_beam/runners/worker/logger.py
    [ 6/11] Cythonizing apache_beam/runners/worker/opcounters.py
    [ 7/11] Cythonizing apache_beam/runners/worker/operations.py
    [ 8/11] Cythonizing apache_beam/runners/worker/statesampler.pyx
    [ 9/11] Cythonizing apache_beam/transforms/cy_combiners.py
    [10/11] Cythonizing apache_beam/utils/counters.py
    [11/11] Cythonizing apache_beam/utils/windowed_value.py
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9m09xu0m/apache-beam/
```

could this just be specific to my machine?

**Comment by tedmiston** [comment]
Ut oh.  This person https://stackoverflow.com/q/46532385/149428 had the same error as you and the answer says that Apache Beam is only compatible with Python 2.7.

I made a Python 2 virtual env and sure enough the 2.4.0 release is there.

```
(tmp-9e8fa979487ff72) t-mbp:tmp-9e8fa979487ff72 taylor$ pip install apache-beam==99999 --no-cache-dir
Collecting apache-beam==99999
  Could not find a version that satisfies the requirement apache-beam==99999 (from versions: 0.6.0, 2.0.0, 2.1.0, 2.1.1, 2.2.0, 2.3.0, 2.4.0)
No matching distribution found for apache-beam==99999
```

So I went back to Python 3 and installed the latest supported version (2.2.0).  However on import it breaks down.

```
>>> import apache_beam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/taylor/.local/share/virtualenvs/tmp-96adc5b8cb5a98d/lib/python3.6/site-packages/apache_beam/__init__.py", line 81, in <module>
    'It is not supported on Python ['+ str(sys.version_info) + '].')
RuntimeError: The Apache Beam SDK for Python is supported only on Python 2.7. It is not supported on Python [sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)].
```

What it looks like to me is that this package never supported Python 3 but was mistakenly published as compatible with Python 3 for the 2.2.0 release and a few others before it.  Newer versions than 2.2.0 don't show as installable on 3 because it looks like that's when they fixed this bug.  They should remove the old releases from PyPI to make it clear that it's not compatible.

Apache does call out this [Python 2.7 requirement](https://beam.apache.org/get-started/quickstart-py/#check-your-python-version) in the Beam docs, however, they don't explicitly call out incompatibility with Python 3.

Airflow calls this out in their [setup.py](https://github.com/apache/incubator-airflow/blob/8c9d3befb1453e60ad5565f6820908aeb1844326/setup.py#L198-L202) as well:

```
# Snakebite & Google Cloud Dataflow are not Python 3 compatible :'(
if PY3:
    devel_ci = [package for package in devel_all if package not in
                ['snakebite>=2.7.8', 'snakebite[kerberos]>=2.7.8',
                 'google-cloud-dataflow>=2.2.0']]
```

This is pretty inexcusable for Google in 2018... Python 3 has been out for almost a decade now.

To me, this suggests the customer's best workaround would be running this work using DockerOperator or Python 2 virtual envs for now (per the comments I wrote a few months ago for another customer with dependency incompatibility).  Either that or we could start co-supporting Python 2 in parallel on our platform.

**Comment by tedmiston** [comment]
Btw it looks like they're working on Python 3 support - https://issues.apache.org/jira/browse/BEAM-1251 (I'm watching).

I also opened an issue for getting the 5 non-working Python 3 releases removed - https://issues.apache.org/jira/browse/BEAM-4025.

**Comment by tedmiston** [comment]
@vparekh94 Have we resolved this one to the point it can be closed?

**Comment by andscoop** [comment]
@vparekh94 bump

**Comment by vparekh94** [comment]
Sorry guys - 

Yeah I think we can close this for now - nothing we can do to fix it.
