### ISSUE TITLE
Info on running arbitrary bash commands

### ISSUE THREAD

**Issue by vparekh94** [astronomerio/astronomer-ee#69]
From a customer request:
```
So it seems like it runs "apk add" on all the packages in packages.txt. Is there a place to run any arbitrary command like export or gcloud?
```

Is there a way to do this to do this with current EE? It looks like a requirement for some GCP packakges:
https://cloud.google.com/sdk/docs/#deb

**Comment by schnie** [comment]
@vparekh94 yes, they can always add additional commands to the `Dockerfile` that the `astro` command creates in their project directory. Sounds like they just need to add some `RUN` commands to the `Dockerfile` - https://docs.docker.com/engine/reference/builder/#run

**Comment by schnie** [comment]
There's also `ENV`, which can be used to add additional environment variables, rather than running `RUN export BLAH=blah`

**Comment by vparekh94** [comment]
Awesome, thanks for jumping in so quickly @schnie, 

Going to get this added to the docs, but this enough for this issue.
