### ISSUE TITLE
Upgrade pip and setuptools

### ISSUE THREAD

**Issue by vparekh94** [astronomerio/astronomer-ee#73]
The current version of EE is using an older version of pip and setuptools. This is affecting google packages (not just google cloud, but also what's needed for google analytics and other google packages).

https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2990#issuecomment-333943013

So far, I've tried adding
`setuptools==39.0.1` to `requirements.txt`
and 
`RUN pip install --upgrade pip`
to `Dockerfile`

This builds the image, but then I run into permission errors trying to install these packages when jumping  into the docker container.

I think this could be solved by building the image with the right version of pip before trying to install `requirements.txt`

**Comment by andscoop** [comment]
@vparekh94 We are going to update our Airflow Dockerfile and cut a new release. Can you submit a PR with the desired changes to our pip and setuptools install? https://github.com/astronomerio/astronomer/blob/master/docker/platform/airflow/Dockerfile#L52

I believe @schnie will need to do the docker build push.

I can update our charts to look at what will be the 0.1.5 tag

**Comment by tedmiston** [comment]
It'd be weird that pip would be breaking stuff here... the new version (10) has only been out for 3 days.  So unless, the Google packages were updated in the last 3 days and use breaking features in 10, I don't think it's related to the linked issue.

The 9.0.3 version we have been using was the latest stable until 3 days ago.

The setuptools we're running is the latest already.

(I upgraded pip & setuptools to the latest 2 weeks ago - https://github.com/astronomerio/astronomer/blame/d0b481b1c78f7c781faf6e287790b65550267dc7/docker/platform/airflow/Dockerfile#L53)

**Comment by tedmiston** [comment]
merged + approved your pr though.  +1 to what andy said ^ about greg cutting the release.

**Comment by schnie** [comment]
Whoa, hang on here. I had a lot of shit break using pip 10 yesterday. Not sure we want to do this.

**Comment by schnie** [comment]
@vparekh94 @tedmiston Did you guys test this out?

**Comment by tedmiston** [comment]
There was also a PyPI outage that was causing breakage for me yesterday. https://twitter.com/gvanrossum/status/986069012520910848

It seemed to work for Viraj "I was able to successfully build locally with a few requirements in there." so I didn't test this one myself, but I'll give it a go.

**Comment by schnie** [comment]
@vparekh94 did you run a full build from the `astronomerio/astronomer` directory? I'm seeing:
```
Collecting pandas<1.0.0,>=0.17.1 (from apache-airflow[celery,devel_ci,redis,statsd])
  Downloading https://files.pythonhosted.org/packages/08/01/803834bc8a4e708aedebb133095a88a4dad9f45bbaf5ad777d2bea543c7e/pandas-0.22.0.tar.gz (11.3MB)
  Could not find a version that satisfies the requirement Cython (from versions: )
No matching distribution found for Cython
The command '/bin/sh -c apk add --no-cache --virtual .build-deps                build-base              cyrus-sasl-dev          freetype-dev            git             krb5-dev                libffi-dev          libxml2-dev              libxslt-dev             linux-headers           mariadb-dev             postgresql-dev          python3-dev     && apk add --no-cache           bash            mariadb-client-libs         postgresql               python3                 tini    && pip3 install --no-cache-dir --upgrade pip==10.0.0    && pip3 install --no-cache-dir --upgrade setuptools==39.0.1     && pip3 install --no-cache-dir "${AIRFLOW_MODULE}"   && apk del .build-deps  && ln -sf /usr/bin/python3 /usr/bin/python      && ln -sf /usr/bin/pip3 /usr/bin/pip' returned a non-zero code: 1
```

**Comment by vparekh94** [comment]
Ahh, I did not run from there - I was building through adding an extra RUN command to upgrade pip.

Should we roll this back and proceed with adding things to `requirements.txt` in the short term?

**Comment by schnie** [comment]
If that fixes it for your specific problem, then yea just add it to `requirements.txt`.

**Comment by tedmiston** [comment]
I wouldn't put pip or setuptools in the requirements.txt but anything else yeah.

**Comment by tedmiston** [comment]
The way we do it already is the best way: keep the packaging tooling in place in stable before packages are installed.

Unless you have a package that fails via requirements.txt install... there are some edge cases and extra flags you can set via `pip install ...` for 1 package that aren't possible when it's bulk installing all of them via `pip install -r requirements.txt`.

If you have a package that known fails via the requirements.txt approach, we can open a dedicated issue for each one.  It's possible one or more of the Google packages are edge cases.

**Comment by andscoop** [comment]
@vparekh94 What did you end up doing here? Are we good to close this out?

**Comment by vparekh94** [comment]
Yeah, we can close. In the short term, I just added pip==10.0.0 to `requirements.txt` and that fixed the issue.
