### ISSUE TITLE
Logs from task instances link to localhost

### ISSUE THREAD

**Issue by vparekh94** [astronomerio/astronomer-ee#74]
When accessing logs from Browse -> Task Instances ->  Log URI, the link goes to localhost instead of the log file (which can be accessed just fine from Graph -> Task Instance -> Logs).

This link should also lead to the log file, not back to localhost.

**Comment by schnie** [comment]
I feel like this is an Airflow bug, but maybe we missed something. Haven't had a chance to look into how that url is computed.

**Comment by cwurtz** [comment]
https://github.com/astronomerio/helm.astronomer.io/pull/25

**Comment by cwurtz** [comment]
The overall problem is fixed in v0.2.0 of EE.  I don't see a specific instance here to ensure it is up to date, so I am closing out.
