### ISSUE TITLE
Secret names no longer match defaults

### ISSUE THREAD

**Issue by schnie** [astronomerio/astronomer-ee#83]
Looks like our docs got out of sync of what we actually have in the helm charts.

**Comment by schnie** [comment]
@cwurtz any idea why we changed these? The GCP docs use secret names that no longer match https://github.com/astronomerio/helm.astronomer.io/blob/master/charts/airflow/values.yaml#L56-L59.

**Comment by cwurtz** [comment]
They were removed from the docs because we no longer do the airflow install by default.  The secrets currently documented are set for the astronomer chart to use.  Houston/Commander will override airflow values with the secrets that get set specific to each airflow install

**Comment by schnie** [comment]
:+1:
