### ISSUE TITLE
Grafana secret missing

### ISSUE THREAD

**Issue by schnie** [astronomerio/astronomer-ee#84]
Looks like the GCP docs removed the Grafana secret.

**Comment by schnie** [comment]
@cwurtz @andscoop any idea what happened to Grafana secret?

**Comment by cwurtz** [comment]
Grafana secret was removed from the docs because airflow is no longer installed by default.  It will be generated when airflow is installed by commander/houston

**Comment by schnie** [comment]
:+1:
