### ISSUE TITLE
auto-restart scheduler

### ISSUE THREAD

**Issue by ryw** [astronomerio/astronomer-ee#96]
Should monitoring stack should trigger notification and restart of scheduler if expected dags don’t run, and email alert should summarize the backlog - might be a nice feature, since it's usually the first manual troubleshooting step.

**Comment by schnie** [comment]
I think we can handle this issue with our health check on the scheduler. Discussed with with Max yesterday, we can probably include a bash or python script to ping the database and do some quick math to determine if the scheduler hasn't heartbeated in a few intervals. Should turn the frequency of the health check to match the scheduler loop interval to avoid unnecessarily slamming the database with little requests.

@andscoop sound right?

**Comment by tedmiston** [comment]
just throwing an idea out there - but i think we could have an alert in prometheus that triggered a scheduler restart e.g. if heartbeat went above a certain threshold.  but building it into the health check sounds nice too.

**Comment by schnie** [comment]
If we come up with a good health check, I think it's the way to go since it wouldn't really depend on Kubernetes and/or the rest of the monitoring stack being around. If we can't figure something clean out there, this might be the next option.
