### ISSUE TITLE
Telemetry - Guide - Monitoring

### ISSUE THREAD

**Issue by tedmiston** [astronomerio/astronomer-ee#97]
This is related to the work I'm doing for monitoring and telemetry for 0.3.0.  Ry mentioned adding this in a Slack thread today.

I started this today and will revisit it once the monitoring feature work is complete.

https://github.com/astronomerio/astronomer-ee/compare/monitoring-guide

@petedejoy @ryw @schnie Can you look at the outline I added in the link and let me know if there's anything you'd like to see added/changed?  I plan to flesh out the details to fill in the outline after the feature work is completed.

**Comment by ryw** [comment]
outline looks good - let's fill in details today

**Comment by tedmiston** [comment]
done via https://github.com/astronomerio/astronomer-ee/pull/98
